# Generated by Django 3.2.4 on 2022-03-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_auto_20220328_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
