# Generated by Django 3.2.4 on 2022-03-28 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_rename_comment_comment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='date',
        ),
    ]
