# Generated by Django 3.2.4 on 2022-03-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0028_alter_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to=''),
        ),
    ]
